### ISSUE TITLE
* Setting work mode to: usb_product    [WTF]

### ISSUE THREAD

**Issue by tribalart** [lolet/FELix#1]
hello , im new to this, i installed a wrong recovery (CWM) on a q102 A31S tablet . (fusion5 finite4)
so i try to re install firmware with felix (win8 , 32bit) i got this error : 

C:\Windows\System32>ruby c:\felix-master\felix --tofes c:\android-adb\sun6.img
FELix 1.0 RC4 by Lolet
## Warning: I don't give any warranty on this software. You use it at own risk!
- Connecting to device at port 1, FEL device 4@2 1f3a:efe8      [OK]
- Checking device info                                          [OK]
- Setting work mode to: usb_product                             [WTF]
  undefined method `&' for 1241579520.0:Float at (eval):19:in`value_to_binary_str
  ing'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/base_primitive.rb:
  128:in `do_write'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/struct.rb:136:in`
  block in do_write'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/struct.rb:136:in `
  each'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/struct.rb:136:in`
  do_write'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/base.rb:167:in `wr
  ite'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/base.rb:180:in`to
  _binary_s'
  c:/felix-master/FELCmds.rb:85:in `transfer'
  c:/felix-master/FELCmds.rb:214:in`write'
  c:/felix-master/FELSuit.rb:311:in `boot_to_fes'
  c:/felix-master/felix:838:in`<main>'
- Cleaning up                                                   [OK]

i dont understand what this mean ?

and so, i cant --felix nand on or off ,
its fail to set flash mode .
or cant use this    felix --write boot0_nand.fex -c fes -t boot0 -a 0

sometime , its just stuck at setting work mode to: usb_product, with no error .

**Comment by jankowskib** [comment]
Tested that and it appears it's Windows only issue. I'll checkout a workaround just in a moment.

**Comment by tribalart** [comment]
its working fine now, thanks you :)

**Comment by tribalart** [comment]
hello i dont know if its related or not :

when i try :

c:\android-adb>ruby c:\felix-master\felix --write  c:\android-adb\sunxi_mbr.fex
--item mbr
FELix 1.0 RC4 by Lolet
Warning: I don't give any warranty on this software. You use it at own risk!
────────────────────────────────────
- Connecting to device at port 3, FEL device 7@2 1f3a:efe8      [OK]
- Read file (1 bytes)                                           [OK]
- fes: Reading MBR                                              [WTF]
  value '        ' not as expected for obj.magic at C:/Ruby200/lib/ruby/gems/2.0.0
  /gems/bindata-2.1.0/lib/bindata/base_primitive.rb:189:in `assert!'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/base_primitive.rb:
  172:in`do_read'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/struct.rb:131:in `
  block in do_read'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/struct.rb:131:in`
  each'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/struct.rb:131:in `
  do_read'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/base.rb:146:in`re
  ad'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/bindata-2.1.0/lib/bindata/base.rb:23:in `rea
  d'
  c:/felix-master/felix:684:in`<main>'
- Cleaning up                                                   [OK]

c:\android-adb>

**Comment by jankowskib** [comment]
Nope, that's unrelated. Your device doesn't have written MBR, you must use --mbr comand to write it. Please open a new issue if you find any problem.
