### ISSUE TITLE
Hello and thanks for great appa

### ISSUE THREAD

**Issue by Tigrouzen** [lolet/FELix#2]
i got this now on ubuntu  15.10

[FATAL] undefined local variable or method `dev' for #FELSuit:0x000000029aea50

**Comment by jankowskib** [comment]
What is your Ruby version and what command did you use?

**Comment by jankowskib** [comment]
Hmm I made silly typo. Sorry for that. Apply commit https://github.com/lolet/FELix/commit/01a39b403ce3d57b59d0a89190bda3f7776fb930
Let me know if you still have any issues

**Comment by Tigrouzen** [comment]
Ok thanks im gonna try

**Comment by Tigrouzen** [comment]
Ruby 2.2.4

https://github.com/lolet/FELix/pull/3/commits/c3021ccccb3a962dedfb50515990920555215a23 : 
- Connecting to device at port 2, FEL device 3@28 1f3a:efe8 [OK]
  magic                  AWUSBFEX
  board                  Allwinner A31 (sun6i), revision 0
  fw                     1
  mode                   fel
  data_flag              0x00000044
  data_length            0x00000008
  data_start_address     0x00007e00
  reserved               [0, 0, 0, 0, 0, 0, 0, 0]
- Cleaning up                                               [OK]
